#!/bin/bash


# Set decoration geometry
berryc border_width       3
berryc inner_border_width 3
berryc title_height       30
berryc top_gap            50

# Set decoration colors
berryc focus_color         292D3E
berryc unfocus_color       292D3E
berryc inner_focus_color   676793
berryc inner_unfocus_color 3c3c56
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Dina-9"

export LC_ALL=C
sxhkd -c /home/zelly/.config/berry/sxhkdrc &
picom --experimental-backends &
feh --bg-scale /home/zelly/Pictures/wallpaper.jpg
/home/zelly/.config/polybar/colorblocks/launch.sh
